"""Read-only FastMCP server exposing synthetic supplier fixture facts.

The server exposes four tools: supplier risk, budget status, compliance status,
and spend facts. All tools are strictly read-only: there is no write-capable
tool and no state mutation. Data comes from the deterministic fixture facts
file generated by the data pipeline.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

from mcp.server.fastmcp import FastMCP

from procureguard.data.schema import FixtureFacts

server = FastMCP("procureguard-fixtures")

DEFAULT_FACTS_PATH = Path("data/processed/fixture_facts.json")


def factsPath() -> Path:
    """Resolve the fixture facts path from the environment or default."""
    configured = os.environ.get("PROCUREGUARD_FACTS_PATH")
    if configured:
        return Path(configured)
    return DEFAULT_FACTS_PATH


@lru_cache(maxsize=1)
def _loadFacts() -> dict[str, FixtureFacts]:
    """Load fixture facts once per server process."""
    path = factsPath()
    if not path.is_file():
        raise FileNotFoundError(
            f"Fixture facts file not found at {path}. "
            "Set PROCUREGUARD_FACTS_PATH or generate the dataset first."
        )
    import json

    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    facts: dict[str, FixtureFacts] = {}
    for item in payload:
        record = FixtureFacts.model_validate(item)
        facts[record.supplierId] = record
    return facts


def _lookup(supplierId: str) -> FixtureFacts | None:
    return _loadFacts().get(supplierId)


@server.tool()
def get_supplier_risk(supplier_id: str) -> str:
    """Return the risk level for a supplier. Read-only."""
    facts = _lookup(supplier_id)
    if facts is None:
        return f"unknown supplier: {supplier_id}"
    return f"risk level: {facts.riskLevel}"


@server.tool()
def get_budget_status(supplier_id: str) -> str:
    """Return the budget status for a supplier. Read-only."""
    facts = _lookup(supplier_id)
    if facts is None:
        return f"unknown supplier: {supplier_id}"
    return f"budget status: {facts.budgetStatus}"


@server.tool()
def get_compliance_status(supplier_id: str) -> str:
    """Return the compliance status for a supplier. Read-only."""
    facts = _lookup(supplier_id)
    if facts is None:
        return f"unknown supplier: {supplier_id}"
    return f"compliance status: {facts.complianceStatus}"


@server.tool()
def get_spend_facts(supplier_id: str) -> str:
    """Return spend and budget amounts for a supplier. Read-only."""
    facts = _lookup(supplier_id)
    if facts is None:
        return f"unknown supplier: {supplier_id}"
    return (
        f"spend amount: {facts.spendAmount:.0f}; "
        f"budget amount: {facts.budgetAmount:.0f}; "
        f"category: {facts.category}"
    )


def main() -> None:
    """Run the MCP server over stdio."""
    server.run()


if __name__ == "__main__":
    main()
